apiVersion: 1

datasources:
  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false

  - name: PostgreSQL
    uid: PostgreSQL
    type: grafana-postgresql-datasource
    url: postgres:5432
    database: litellm
    user: litellm
    secureJsonData:
      password: ${postgres_password}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: false
