# =========================================================================
# InsideLLM - WSL2 Deployment Command
# Generated by Setup Wizard on 2026-03-26
#
# Run this in PowerShell as Administrator
# =========================================================================

.\Install-InsideLLM-WSL.ps1 `
    -AnthropicApiKey "YOUR_API_KEY_HERE" `
    -OllamaGpu $true `
    -Domain "uniformedi.local" `
    -Owner "Uniformedi"
